# DEVELO LIBRARY MAKEFILE [MSDOS]
#

RM       = del
CC       = gcc

CFLAGS   = -O -Wall
OBJS     = init.o xfer.o error.o command.o mx.o slave.o
LIB      = libdevel.a
TARGETS  = $(LIB)

#
#

all: $(TARGETS)

# CLEAN
#
clean:
	$(RM) *.o
	$(RM) libdevel.a

# RULES
#
$(OBJS) : develo.h
xfer.o  : crc16.h 
%.o : %.c
	$(CC) $(CFLAGS) -o $@ -c $<

# EXE
#
$(LIB): $(OBJS)
	ar rs $(LIB) $(OBJS)

